[package]
name = "sk"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"
glob = "0.3.1"
reqwest = { version = "0.12", features = ["blocking"] }
serde = { version = "1.0", features = ["derive"] }
toml = "0.8.19"
